cp -r classes AppDir/usr/share/my_project/
cp -r mbientlab AppDir/usr/share/my_project/
cp -r qt_project AppDir/usr/share/my_project/
cp -r services AppDir/usr/share/my_project/
cp -r submodule AppDir/usr/share/my_project/
cp -r log_setup.py AppDir/usr/share/my_project/
cp -r main.py AppDir/usr/share/my_project/
cp -r settings.py AppDir/usr/share/my_project/
cp -r classes AppDir/usr/share/my_project/