# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_controller_system.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import logging

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChart, QChartView, QLineSeries
from PyQt5.QtGui import QPainter, QPen

from settings import (BITA_OSC_PATH_POS, BITA_OSC_PATH_PRY, BITA_PORT,
                      DEVICE_MAC, POS_STEP)

logger = logging.getLogger(__name__)

class Ui_MainScreen(QtWidgets.QMainWindow):
    data_signal = QtCore.pyqtSignal(list)
    def __init__(self, osc_client, devices, osc_functions, devices_function, devices_ip, osc_ip):
        super().__init__()
        self.osc_client = osc_client
        self.devices = devices
        self.osc_functions = osc_functions
        self.devices_function = devices_function
        self.devices_ip = devices_ip
        self.osc_ip = osc_ip
        self.max_points = 5000
        self.counter = 0
        self.setupUi(self)
        self.data_signal.connect(self.update_data)
        self.CHART_POINTS_VISUALIZATION_INTERVAL = 20 # Represento uno de cada 20 puntos

    
    
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(1024, 840)

        self.central_widget = QtWidgets.QWidget(MainScreen)
        MainScreen.setCentralWidget(self.central_widget)

        self.vertical_layout = QtWidgets.QVBoxLayout(self.central_widget)

        self.tabWidget = QtWidgets.QTabWidget(self.central_widget)
        self.vertical_layout.addWidget(self.tabWidget)

        self.setup_osc_tab()
        self.setup_general_configuration_tab()
        self.setup_visualization_tab()

        self.tabWidget.setCurrentIndex(1)  # Iniciar en la segunda pestaña

        # self.buttonBox = QtWidgets.QDialogButtonBox(QtWidgets.QDialogButtonBox.Apply | QtWidgets.QDialogButtonBox.Close | QtWidgets.QDialogButtonBox.RestoreDefaults, self.central_widget)
        # self.vertical_layout.addWidget(self.buttonBox)

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

        # Connect signals
        self.setup_connections()

    def setup_osc_tab(self):
        self.tab_configuration_osc = QtWidgets.QWidget()
        self.tab_configuration_osc.setObjectName("tab_configuration_osc")
        
        self.grid_layout_osc = QtWidgets.QGridLayout(self.tab_configuration_osc)
        
        self.checkBox_osc_is_enabled = QtWidgets.QCheckBox(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.checkBox_osc_is_enabled, 0, 0, 1, 2)
        
        self.label_ip = QtWidgets.QLabel(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.label_ip, 1, 0)
        
        self.comboBox_aviable_ips = QtWidgets.QComboBox(self.tab_configuration_osc)
        self.comboBox_aviable_ips.setEditable(True)
        self.grid_layout_osc.addWidget(self.comboBox_aviable_ips, 1, 1)
        
        self.label_puerto = QtWidgets.QLabel(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.label_puerto, 2, 0)
        
        self.lineEdit_port = QtWidgets.QLineEdit(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.lineEdit_port, 2, 1)
        
        self.label_osc_pry = QtWidgets.QLabel(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.label_osc_pry, 3, 0)
        
        self.lineEdit_osc_path_pry = QtWidgets.QLineEdit(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.lineEdit_osc_path_pry, 3, 1)
        
        self.label_osc_pos = QtWidgets.QLabel(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.label_osc_pos, 4, 0)
        
        self.lineEdit_osc_path_pos = QtWidgets.QLineEdit(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.lineEdit_osc_path_pos, 4, 1)
        
        self.tabWidget.addTab(self.tab_configuration_osc, "")

    def setup_general_configuration_tab(self):
        self.tab_configuration_general = QtWidgets.QWidget()
        self.tab_configuration_general.setObjectName("tab_configuration_general")
        
        self.grid_layout_general = QtWidgets.QGridLayout(self.tab_configuration_general)
        
        self.label_mac = QtWidgets.QLabel(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.label_mac, 0, 0)
        
        self.lineEdit_device_mac = QtWidgets.QLineEdit(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.lineEdit_device_mac, 0, 1)
        
        self.label_step_size = QtWidgets.QLabel(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.label_step_size, 1, 0)
        
        self.spinBox_step_size = QtWidgets.QSpinBox(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.spinBox_step_size, 1, 1)
        
        self.pushButton_connect = QtWidgets.QPushButton(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.pushButton_connect, 2, 0)
        
        self.pushButton_disconnect = QtWidgets.QPushButton(self.tab_configuration_general)
        self.pushButton_disconnect.setEnabled(False)
        self.grid_layout_general.addWidget(self.pushButton_disconnect, 2, 1)
        
        self.tabWidget.addTab(self.tab_configuration_general, "")
        logger.info(f"Añadiendo IPs: {self.devices_ip}")
        self.comboBox_aviable_ips.addItems(self.devices_ip)
        if len(self.devices_ip) > 0:
            self.comboBox_aviable_ips.setEditText(self.devices_ip[0])
        
    def setup_visualization_tab(self):
        self.tab_visualization = QtWidgets.QWidget()
        self.tab_visualization.setObjectName("tab_visualization")
        
        self.grid_layout_visualization = QtWidgets.QGridLayout(self.tab_visualization)
        
        self.label_graphics_title = QtWidgets.QLabel(self.tab_visualization)
        self.grid_layout_visualization.addWidget(self.label_graphics_title, 0, 0, 1, 2)
        
        self.chart_view = QChartView(self.tab_visualization)
        self.chart_view.setRenderHint(QPainter.Antialiasing)
        self.grid_layout_visualization.addWidget(self.chart_view, 1, 0, 1, 6)
        
        self.series_yaw = QLineSeries()
        self.series_pitch = QLineSeries()
        self.series_roll = QLineSeries()
        self.series_heading = QLineSeries()
        
        self.series_yaw.setName("Yaw")
        self.series_pitch.setName("Pitch")
        self.series_roll.setName("Roll")
        self.series_heading.setName("Heading")
        
        self.chart = QChart()
        self.chart.addSeries(self.series_yaw)
        self.chart.addSeries(self.series_pitch)
        self.chart.addSeries(self.series_roll)
        self.chart.addSeries(self.series_heading)
        self.chart.createDefaultAxes()
        self.chart.legend().setVisible(True)
        self.chart.legend().setAlignment(QtCore.Qt.AlignBottom)
        self.chart_view.setChart(self.chart)

        self.lcd_displays = {}
        for i, label in enumerate(["YAW", "PITCH", "ROLL", "X", "Y", "Z"]):
            label_widget = QtWidgets.QLabel(self.tab_visualization)
            label_widget.setText(label)
            self.grid_layout_visualization.addWidget(label_widget, 2 + i // 3, (i % 3) * 2)
            
            lcd_widget = QtWidgets.QLCDNumber(self.tab_visualization)
            lcd_widget.setSmallDecimalPoint(True)
            self.grid_layout_visualization.addWidget(lcd_widget, 2 + i // 3, (i % 3) * 2 + 1)
            self.lcd_displays[label.lower()] = lcd_widget

        self.pushButton_calibrate = QtWidgets.QPushButton(self.tab_visualization)
        self.pushButton_calibrate.setObjectName("pushButton_calibrate")
        self.grid_layout_visualization.addWidget(self.pushButton_calibrate, 4, 3)

        self.setup_control_buttons()

        self.tabWidget.addTab(self.tab_visualization, "")

    def setup_visualization_tab(self):
        self.tab_visualization = QtWidgets.QWidget()
        self.tab_visualization.setObjectName("tab_visualization")

        self.grid_layout_visualization = QtWidgets.QGridLayout(self.tab_visualization)

        self.label_graphics_title = QtWidgets.QLabel(self.tab_visualization)
        self.grid_layout_visualization.addWidget(self.label_graphics_title, 0, 0, 1, 6)

        self.chart_view = QChartView(self.tab_visualization)
        self.chart_view.setRenderHint(QPainter.Antialiasing)
        self.grid_layout_visualization.addWidget(self.chart_view, 1, 0, 1, 6)

        self.series_yaw = QLineSeries()
        self.series_pitch = QLineSeries()
        self.series_roll = QLineSeries()
        self.series_heading = QLineSeries()

        self.series_yaw.setName("Yaw")
        self.series_pitch.setName("Pitch")
        self.series_roll.setName("Roll")
        self.series_heading.setName("Heading")
        self.series_yaw.setPen(QPen(QtCore.Qt.red))
        self.series_pitch.setPen(QPen(QtCore.Qt.green))
        self.series_roll.setPen(QPen(QtCore.Qt.blue))
        self.series_heading.setPen(QPen(QtCore.Qt.gray))
        self.chart = QChart()
        self.chart.addSeries(self.series_yaw)
        self.chart.addSeries(self.series_pitch)
        self.chart.addSeries(self.series_roll)
        self.chart.addSeries(self.series_heading)

        self.chart.createDefaultAxes()
        self.chart.legend().setVisible(True)
        self.chart.legend().setAlignment(QtCore.Qt.AlignBottom)
        self.chart_view.setChart(self.chart)
        self.chart.axisY().setRange(0, 7)
        self.chart.axisX().setRange(0, self.max_points)
        
        # for x in range(0, self.max_points):
        #     self.add_point

        self.lcd_displays = {}
        labels = ["YAW", "PITCH", "ROLL", "X", "Y", "Z"]
        for i, label in enumerate(labels):
            label_widget = QtWidgets.QLabel(self.tab_visualization)
            label_widget.setText(label)
            row = 2 + (i % 3)
            col = (i // 3) * 2
            self.grid_layout_visualization.addWidget(label_widget, row, col)
            
            lcd_widget = QtWidgets.QLCDNumber(self.tab_visualization)
            lcd_widget.setSmallDecimalPoint(True)
            self.grid_layout_visualization.addWidget(lcd_widget, row, col + 1)
            self.lcd_displays[label.lower()] = lcd_widget

        self.pushButton_calibrate = QtWidgets.QPushButton(self.tab_visualization)
        self.pushButton_calibrate.setObjectName("pushButton_calibrate")
        self.grid_layout_visualization.addWidget(self.pushButton_calibrate, 5, 5)

        self.setup_control_buttons()

        self.tabWidget.addTab(self.tab_visualization, "")

    def setup_control_buttons(self):
        control_buttons = {
            "↑": (0, 1),
            "↓": (1, 1),
            "→": (1, 2),
            "←": (1, 0),
            "⇧": (0, 3),
            "⇩": (1, 3)
        }
        control_buttons_functions = {
            "↑": "move_up",
            "↓": "move_down"  ,
            "→": "move_right",
            "←": "move_left",
            "⇧": "move_in"  ,
            "⇩": "move_out" ,
        }

        self.grid_layout_controls = QtWidgets.QGridLayout()
        self.grid_layout_visualization.addLayout(self.grid_layout_controls, 2, 4, 3, 2)

        for btn_text, pos in control_buttons.items():
            btn = QtWidgets.QPushButton(self.tab_visualization)
            btn.setText(btn_text)
            font = QtGui.QFont()
            font.setFamily("DejaVu Sans")
            font.setPointSize(25)
            font.setBold(True)
            font.setWeight(75)
            btn.setFont(font)
            btn.setAutoRepeat(True)
            self.grid_layout_controls.addWidget(btn, pos[0], pos[1])
            #btn.clicked.connect(lambda _, b=btn_text: self.control_button_clicked(b))#
            btn.clicked.connect(lambda: self.osc_functions[control_buttons_functions[btn_text]](self.devices, self.osc_client))

    def add_point(self, x, yaw, pitch, roll, heading):
        if len(self.series_yaw) >= self.max_points:
            self.series_yaw.remove(0)
            self.series_pitch.remove(0)
            self.series_roll.remove(0)
            self.series_heading.remove(0)

        self.series_yaw.append(x, yaw)
        self.series_pitch.append(x, pitch)
        self.series_roll.append(x, roll)
        self.series_heading.append(x, heading)

        # Desplaza la gráfica al actualizar los puntos
        if x >= self.max_points:
            self.chart.axisX().setRange(x - self.max_points, x)

    @QtCore.pyqtSlot(list)
    def update_data(self, data):
        self.lcd_displays["yaw"].display(round(data[2], 2))
        self.lcd_displays["pitch"].display(round(data[0], 2))
        self.lcd_displays["roll"].display(round(data[1], 2))
        # self.lcd_displays["yaw"].display(round(data[3], 2))

        # Sólo actualizar 1 de cada 100 puntos
        if self.counter % self.CHART_POINTS_VISUALIZATION_INTERVAL == 0:
            self.add_point(self.counter, data[2], data[0], data[1], data[3])

        self.counter += 1
    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "Control sensor inercial"))
        self.checkBox_osc_is_enabled.setText(_translate("MainScreen", "Habilitar envío por OSC"))
        self.lineEdit_port.setText(_translate("MainScreen", str(BITA_PORT)))
        self.label_ip.setText(_translate("MainScreen", "IP:"))
        self.lineEdit_device_mac.setText(_translate("MainScreen", DEVICE_MAC))
        self.label_puerto.setText(_translate("MainScreen", "Puerto"))
        self.comboBox_aviable_ips.setPlaceholderText(_translate("MainScreen", "Cargando lista de IPs"))
        self.lineEdit_osc_path_pry.setText(_translate("MainScreen", BITA_OSC_PATH_PRY))
        self.lineEdit_osc_path_pry.setPlaceholderText(_translate("MainScreen", "OSC Path - PRY"))
        self.label_osc_pry.setText(_translate("MainScreen", "Path OSC - PRY"))
        self.label_osc_pos.setText(_translate("MainScreen", "Path POS - XYZ"))
        
        self.lineEdit_osc_path_pos.setText(_translate("MainScreen", BITA_OSC_PATH_POS))
        self.lineEdit_osc_path_pos.setPlaceholderText(_translate("MainScreen", "OSC Path - POS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_configuration_osc), _translate("MainScreen", "OSC"))
        self.label_mac.setText(_translate("MainScreen", "Device - MAC"))
        self.label_step_size.setText(_translate("MainScreen", "Step size"))
        self.pushButton_connect.setText(_translate("MainScreen", "Conectar"))
        self.pushButton_disconnect.setText(_translate("MainScreen", "Desconectar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_configuration_general), _translate("MainScreen", "Configuración general"))
        self.pushButton_calibrate.setText(_translate("MainScreen", "Calibrar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_visualization), _translate("MainScreen", "Visualización y controles"))
        self.label_graphics_title.setText(_translate("MainScreen", "Gráfica de orientación en el tiempo"))

    def setup_connections(self):
        self.checkBox_osc_is_enabled.stateChanged.connect(self.osc_functions["set_enable_osc"])
        self.pushButton_connect.clicked.connect(lambda: self.devices_function["connect"](self.lineEdit_device_mac.text()))
        self.pushButton_disconnect.clicked.connect(lambda: self.devices_function["disconnect"]())
        self.pushButton_calibrate.clicked.connect(lambda: self.devices_function["calibrate"](self.devices))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainScreen = QtWidgets.QMainWindow()
    ui = Ui_MainScreen(None, None, {}, {}, [], "")
    ui.setupUi(MainScreen)
    MainScreen.show()
    sys.exit(app.exec_())
