# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_controller_system.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import logging

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChart, QChartView, QLineSeries
from PyQt5.QtGui import QPainter, QPen

from settings import (OSC_RECIVER_PATH_POS, OSC_RECIVER_PATH_PRY, OSC_RECIVER_PORT,
                      IMU_DEVICE_MAC, MODE_SENSOR, MODE_UI, POS_STEP)

logger = logging.getLogger(__name__)

class Ui_MainScreen(QtWidgets.QMainWindow):
    data_signal = QtCore.pyqtSignal(list)
    def __init__(self, osc_client, devices, osc_functions, devices_function, devices_ip, osc_ip):
        super().__init__()
        self.osc_client = osc_client
        self.devices = devices
        self.osc_functions = osc_functions
        self.devices_function = devices_function
        self.devices_ip = devices_ip
        self.osc_ip = osc_ip
        self.max_points = 5000
        self.counter = 0
        self.setupUi(self)
        self.data_signal.connect(self.update_data)
        self.CHART_POINTS_VISUALIZATION_INTERVAL = 20 # Represento uno de cada 20 puntos

    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(1024, 840)

        self.central_widget = QtWidgets.QWidget(MainScreen)
        MainScreen.setCentralWidget(self.central_widget)

        self.vertical_layout = QtWidgets.QVBoxLayout(self.central_widget)

        self.tabWidget = QtWidgets.QTabWidget(self.central_widget)
        self.vertical_layout.addWidget(self.tabWidget)

        self.setup_osc_tab()
        self.setup_general_configuration_tab()
        self.setup_visualization_tab()

        self.tabWidget.setCurrentIndex(1)  # Iniciar en la segunda pestaña

        # self.buttonBox = QtWidgets.QDialogButtonBox(QtWidgets.QDialogButtonBox.Apply | QtWidgets.QDialogButtonBox.Close | QtWidgets.QDialogButtonBox.RestoreDefaults, self.central_widget)
        # self.vertical_layout.addWidget(self.buttonBox)

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

        # Connect signals
        self.setup_connections()

    def setup_osc_tab(self):
        self.tab_configuration_osc = QtWidgets.QWidget()
        self.tab_configuration_osc.setObjectName("tab_configuration_osc")

        self.grid_layout_osc = QtWidgets.QGridLayout(self.tab_configuration_osc)

        self.checkBox_osc_is_enabled = QtWidgets.QCheckBox(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.checkBox_osc_is_enabled, 0, 0, 1, 2)

        self.label_ip = QtWidgets.QLabel(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.label_ip, 1, 0)

        self.comboBox_aviable_ips = QtWidgets.QComboBox(self.tab_configuration_osc)
        self.comboBox_aviable_ips.setEditable(True)
        self.grid_layout_osc.addWidget(self.comboBox_aviable_ips, 1, 1)

        self.label_puerto = QtWidgets.QLabel(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.label_puerto, 2, 0)

        self.lineEdit_port = QtWidgets.QLineEdit(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.lineEdit_port, 2, 1)

        self.label_osc_pry = QtWidgets.QLabel(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.label_osc_pry, 3, 0)

        self.lineEdit_osc_path_pry = QtWidgets.QLineEdit(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.lineEdit_osc_path_pry, 3, 1)

        self.label_osc_pos = QtWidgets.QLabel(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.label_osc_pos, 4, 0)

        self.lineEdit_osc_path_pos = QtWidgets.QLineEdit(self.tab_configuration_osc)
        self.grid_layout_osc.addWidget(self.lineEdit_osc_path_pos, 4, 1)

        self.tabWidget.addTab(self.tab_configuration_osc, "")

    def setup_general_configuration_tab(self):
        self.tab_configuration_general = QtWidgets.QWidget()
        self.tab_configuration_general.setObjectName("tab_configuration_general")

        self.grid_layout_general = QtWidgets.QGridLayout(self.tab_configuration_general)

        self.label_mac = QtWidgets.QLabel(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.label_mac, 0, 0)

        self.lineEdit_device_mac = QtWidgets.QLineEdit(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.lineEdit_device_mac, 0, 1)

        self.label_step_size = QtWidgets.QLabel(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.label_step_size, 1, 0)

        self.spinBox_step_size = QtWidgets.QSpinBox(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.spinBox_step_size, 1, 1)

        self.pushButton_connect = QtWidgets.QPushButton(self.tab_configuration_general)
        self.grid_layout_general.addWidget(self.pushButton_connect, 2, 0)

        self.pushButton_disconnect = QtWidgets.QPushButton(self.tab_configuration_general)
        self.pushButton_disconnect.setEnabled(False)
        self.grid_layout_general.addWidget(self.pushButton_disconnect, 2, 1)

        self.tabWidget.addTab(self.tab_configuration_general, "")
        logger.info(f"Añadiendo IPs: {self.devices_ip}")
        self.comboBox_aviable_ips.addItems(self.devices_ip)
        if len(self.devices_ip) > 0:
            self.comboBox_aviable_ips.setEditText(self.devices_ip[0])

    def setup_visualization_tab(self):
        self.tab_visualization = QtWidgets.QWidget()
        self.tab_visualization.setObjectName("tab_visualization")

        self.grid_layout_visualization = QtWidgets.QGridLayout(self.tab_visualization)

        self.label_graphics_title = QtWidgets.QLabel(self.tab_visualization)
        self.grid_layout_visualization.addWidget(self.label_graphics_title, 0, 0, 1, 2)

        self.chart_view = QChartView(self.tab_visualization)
        self.chart_view.setRenderHint(QPainter.Antialiasing)
        self.grid_layout_visualization.addWidget(self.chart_view, 1, 0, 1, 6)

        self.series_0 = QLineSeries()
        self.series_1 = QLineSeries()
        self.series_2 = QLineSeries()
        self.series_3 = QLineSeries()

        if MODE_UI == "QUATERNIONS":
            axis = ["w", "x", "y", "z"]
        else:
            axis = ["yaw", "pitch", "roll", "heading"]
        self.series_0.setName(axis[0])
        self.series_1.setName(axis[1])
        self.series_2.setName(axis[2])
        self.series_3.setName(axis[3])

        self.chart = QChart()
        self.chart.addSeries(self.series_0)
        self.chart.addSeries(self.series_1)
        self.chart.addSeries(self.series_2)
        self.chart.addSeries(self.series_3)
        self.chart.createDefaultAxes()
        self.chart.legend().setVisible(True)
        self.chart.legend().setAlignment(QtCore.Qt.AlignBottom)
        self.chart_view.setChart(self.chart)

        self.lcd_displays = {}
        if MODE_UI == "QUATERNIONS":
            labels = ["w", "x", "y", "z", "X_POS", "Y_POS", "Z_POS"]
        else:
            labels = ["yaw", "pitch", "roll", "X_POS", "Y_POS", "Z_POS"]
        for i, label in enumerate(labels):
            label_widget = QtWidgets.QLabel(self.tab_visualization)
            label_widget.setText(label)
            self.grid_layout_visualization.addWidget(label_widget, 2 + i // 3, (i % 3) * 2)

            lcd_widget = QtWidgets.QLCDNumber(self.tab_visualization)
            lcd_widget.setSmallDecimalPoint(True)
            self.grid_layout_visualization.addWidget(lcd_widget, 2 + i // 3, (i % 3) * 2 + 1)
            self.lcd_displays[label] = lcd_widget

        self.pushButton_calibrate = QtWidgets.QPushButton(self.tab_visualization)
        self.pushButton_calibrate.setObjectName("pushButton_calibrate")
        self.grid_layout_visualization.addWidget(self.pushButton_calibrate, 4, 3)

        self.setup_control_buttons()

        self.tabWidget.addTab(self.tab_visualization, "")

    def setup_visualization_tab(self):
        self.tab_visualization = QtWidgets.QWidget()
        self.tab_visualization.setObjectName("tab_visualization")

        self.main_layout = QtWidgets.QHBoxLayout(self.tab_visualization)

        # Left layout for labels and LCDs
        self.left_layout = QtWidgets.QVBoxLayout()
        self.main_layout.addLayout(self.left_layout)

        self.labels_lcds_layout = QtWidgets.QGridLayout()
        self.left_layout.addLayout(self.labels_lcds_layout)

        self.lcd_displays = {}
        if MODE_UI == "QUATERNIONS":
            labels = ["w", "x", "y", "z", "X_POS", "Y_POS", "Z_POS"]
        else:
            labels = ["yaw", "pitch", "roll", "X_POS", "Y_POS", "Z_POS"]

        for i, label in enumerate(labels):
            label_widget = QtWidgets.QLabel(self.tab_visualization)
            label_widget.setText(label)
            row = i
            col = 0
            self.labels_lcds_layout.addWidget(label_widget, row, col)

            lcd_widget = QtWidgets.QLCDNumber(self.tab_visualization)
            lcd_widget.setSmallDecimalPoint(True)
            self.labels_lcds_layout.addWidget(lcd_widget, row, col + 1)
            self.lcd_displays[label] = lcd_widget

        self.pushButton_calibrate = QtWidgets.QPushButton(self.tab_visualization)
        self.pushButton_calibrate.setObjectName("pushButton_calibrate")
        self.left_layout.addWidget(self.pushButton_calibrate)

        # Right layout for chart and control buttons
        self.right_layout = QtWidgets.QVBoxLayout()
        self.main_layout.addLayout(self.right_layout)

        self.label_graphics_title = QtWidgets.QLabel(self.tab_visualization)
        self.right_layout.addWidget(self.label_graphics_title)

        self.chart_view = QChartView(self.tab_visualization)
        self.chart_view.setRenderHint(QPainter.Antialiasing)
        self.right_layout.addWidget(self.chart_view)

        self.series_0 = QLineSeries()
        self.series_1 = QLineSeries()
        self.series_2 = QLineSeries()
        self.series_3 = QLineSeries()
        if MODE_UI == "QUATERNIONS":
            axis = ["w", "x", "y", "z"]
        else:
            axis = ["yaw", "pitch", "roll", "heading"]
        self.series_0.setName(axis[0])
        self.series_1.setName(axis[1])
        self.series_2.setName(axis[2])
        self.series_3.setName(axis[3])
        self.series_0.setPen(QPen(QtCore.Qt.red))
        self.series_1.setPen(QPen(QtCore.Qt.green))
        self.series_2.setPen(QPen(QtCore.Qt.blue))
        self.series_3.setPen(QPen(QtCore.Qt.gray))
        self.chart = QChart()
        self.chart.addSeries(self.series_0)
        self.chart.addSeries(self.series_1)
        self.chart.addSeries(self.series_2)
        self.chart.addSeries(self.series_3)

        self.chart.createDefaultAxes()
        self.chart.legend().setVisible(True)
        self.chart.legend().setAlignment(QtCore.Qt.AlignBottom)
        self.chart_view.setChart(self.chart)
        if MODE_UI == "QUATERNIONS":
            MAX_RANGE = 1
            MIN_RANGE = -1
        else:
            MIN_RANGE = 0
            MAX_RANGE = 7
        self.chart.axisY().setRange(MIN_RANGE, MAX_RANGE)
        self.chart.axisX().setRange(0, self.max_points)

        self.setup_control_buttons()

        self.tabWidget.addTab(self.tab_visualization, "")

    def setup_control_buttons(self):
        control_buttons = {
            "↑": (0, 1),
            "↓": (1, 1),
            "→": (1, 2),
            "←": (1, 0),
            "⇧": (0, 3),
            "⇩": (1, 3)
        }
        control_buttons_functions = {
            "↑": "move_up",
            "↓": "move_down",
            "→": "move_right",
            "←": "move_left",
            "⇩": "move_out",
            "⇧": "move_in",
        }

        self.grid_layout_controls = QtWidgets.QGridLayout()
        self.right_layout.addLayout(self.grid_layout_controls)
        btns = {}
        for btn_text, pos in control_buttons.items():
            btns[btn_text] = QtWidgets.QPushButton(self.tab_visualization)

            btns[btn_text].setText(btn_text)
            font = QtGui.QFont()
            font.setFamily("DejaVu Sans")
            font.setPointSize(25)
            font.setBold(True)
            font.setWeight(75)
            btns[btn_text].setFont(font)
            btns[btn_text].setAutoRepeat(True)
            self.grid_layout_controls.addWidget(btns[btn_text], pos[0], pos[1])
            logger.info(
                f"Seteando callback - {btn_text} -> {control_buttons_functions[btn_text]}"
            )
            btns[btn_text].clicked.connect(
                lambda _, b=btn_text: self.osc_functions[
                    control_buttons_functions[btn_text]
                ](self.devices, self.osc_client)
            )

    def add_point(self, x, yaw, pitch, roll, heading):
        if len(self.series_0) >= self.max_points:
            self.series_0.remove(0)
            self.series_1.remove(0)
            self.series_2.remove(0)
            self.series_3.remove(0)

        self.series_0.append(x, yaw)
        self.series_1.append(x, pitch)
        self.series_2.append(x, roll)
        self.series_3.append(x, heading)

        # Desplaza la gráfica al actualizar los puntos
        if x >= self.max_points:
            self.chart.axisX().setRange(x - self.max_points, x)

    @QtCore.pyqtSlot(list)
    def update_data(self, data):
        if MODE_UI == "QUATERNIONS":
            LCDS = ["w", "z", "x", "y"]
        else:
            LCDS = ["pitch", "roll", "yaw"]
        for i, lcd in enumerate(LCDS): 
            self.lcd_displays[lcd].display(round(data[i], 2))

        # Sólo actualizar 1 de cada 100 puntos
        if self.counter % self.CHART_POINTS_VISUALIZATION_INTERVAL == 0:
            if MODE_UI == "QUATERNIONS":
                self.add_point(
                    self.counter,
                    # data[0],w
                    # data[2],z
                    # data[3],x
                    # data[1],y
                    data[0],
                    data[1],
                    data[2],
                    data[3]
                )
            else:
                self.add_point(
                    self.counter,
                    data[2],
                    data[0],
                    data[1],
                    0 if len(data) < 4 else data[3],
                )

        self.counter += 1
    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "Control sensor inercial"))
        self.checkBox_osc_is_enabled.setText(_translate("MainScreen", "Habilitar envío por OSC"))
        self.lineEdit_port.setText(_translate("MainScreen", str(OSC_RECIVER_PORT)))
        self.label_ip.setText(_translate("MainScreen", "IP:"))
        self.lineEdit_device_mac.setText(_translate("MainScreen", IMU_DEVICE_MAC))
        self.label_puerto.setText(_translate("MainScreen", "Puerto"))
        self.comboBox_aviable_ips.setPlaceholderText(_translate("MainScreen", "Cargando lista de IPs"))
        self.lineEdit_osc_path_pry.setText(_translate("MainScreen", OSC_RECIVER_PATH_PRY))
        self.lineEdit_osc_path_pry.setPlaceholderText(_translate("MainScreen", "OSC Path - PRY"))
        self.label_osc_pry.setText(_translate("MainScreen", "Path OSC - PRY"))
        self.label_osc_pos.setText(_translate("MainScreen", "Path POS - XYZ"))

        self.lineEdit_osc_path_pos.setText(_translate("MainScreen", OSC_RECIVER_PATH_POS))
        self.lineEdit_osc_path_pos.setPlaceholderText(_translate("MainScreen", "OSC Path - POS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_configuration_osc), _translate("MainScreen", "OSC"))
        self.label_mac.setText(_translate("MainScreen", "Device - MAC"))
        self.label_step_size.setText(_translate("MainScreen", "Step size"))
        self.spinBox_step_size.setValue(POS_STEP)
        self.pushButton_connect.setText(_translate("MainScreen", "Conectar"))
        self.pushButton_disconnect.setText(_translate("MainScreen", "Desconectar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_configuration_general), _translate("MainScreen", "Configuración general"))
        self.pushButton_calibrate.setText(_translate("MainScreen", "Calibrar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_visualization), _translate("MainScreen", "Visualización y controles"))
        self.label_graphics_title.setText(_translate("MainScreen", "Gráfica de orientación en el tiempo"))

    def setup_connections(self):
        self.checkBox_osc_is_enabled.stateChanged.connect(self.osc_functions["set_enable_osc"])
        self.pushButton_connect.clicked.connect(lambda: self.devices_function["connect"](self.lineEdit_device_mac.text()))
        self.pushButton_disconnect.clicked.connect(lambda: self.devices_function["disconnect"]())
        self.pushButton_calibrate.clicked.connect(lambda: self.devices_function["calibrate"](self.devices))
        self.spinBox_step_size.valueChanged.connect(set_pos_step)

def set_pos_step(value):
    global POS_STEP
    POS_STEP = value

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainScreen = QtWidgets.QMainWindow()
    ui = Ui_MainScreen(None, None, {}, {}, [], "")
    ui.setupUi(MainScreen)
    MainScreen.show()
    sys.exit(app.exec_())
